### ISSUE TITLE
Add the native RetroAchievements capability

### ISSUE THREAD

**Issue by alondero** [alondero/nestlin#267]
## Parent

Part of #265.

## What to build

Make the official RetroAchievements runtime an optional, observable Nestlin capability by integrating pinned `rcheevos` v12.4.0 behind a small flat native façade and the service seam introduced in #266.

Vendor the exact upstream source and required license notices so builds are reproducible. The C façade owns all `rc_client` pointers, structures, borrowed strings, callback contexts, and destruction order. JNA may expose only a flat ABI and copied immutable values to Kotlin; Kotlin must never retain native-owned pointers or strings. Callback objects must remain strongly reachable for the complete client lifetime.

Force softcore mode immediately after client creation. This ticket does not implement real account login or game activation, but it must prove the native client can be created, queried for its pinned version, and destroyed safely. It must also expose available/unavailable state through the RetroAchievements menu so users understand whether their platform supports the feature.

When the bundled library is absent, has the wrong version/checksum/architecture, or fails to load, Nestlin must continue as a fully usable emulator through the no-op service. Headless tools and tests that do not explicitly request the native contract must not load it.

## Acceptance criteria

- [ ] Exact `rcheevos` v12.4.0 source and applicable license notices are vendored reproducibly.
- [ ] A small C façade exposes only the operations and copied values needed by the service; `rc_client` internals do not cross into Kotlin.
- [ ] JNA creates and destroys a native client safely, validates the pinned runtime version, and holds callbacks strongly for their lifetime.
- [ ] The client is forced into softcore mode with no hardcore toggle.
- [ ] Native callback teardown is safe when work is pending or application shutdown occurs.
- [ ] A native contract test creates/destroys the client, reads the pinned version, and exercises representative callback ownership without production network access.
- [ ] Missing, corrupt, incompatible, or unsupported native libraries select the no-op implementation and do not prevent startup or gameplay.
- [ ] The RetroAchievements menu exposes a clear unavailable explanation or a signed-out/available state.
- [ ] Headless replay, bootcheck, and unrelated unit tests neither load the native library nor acquire a network dependency.
- [ ] Logs and exceptions contain no borrowed native memory or sensitive request contents.
- [ ] Existing emulator behavior and deterministic tooling remain unchanged.

## Blocked by

- #266

## Blocks

- #268
